"""
Dimension Constants

Frame sizes, UI element sizes, and spatial constants.
"""

# === FRAME DIMENSIONS ===
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

# === HAND RENDERING ===
HAND_CONNECTOR_THICKNESS = 20
HAND_LANDMARK_RADIUS = 5

# === WEB RENDERING ===
WEB_LINE_THICKNESS = 3
WEB_GLOW_THICKNESS = 8

# === SYMBIOTE RENDERING ===
SYMBIOTE_GLOW_RADIUS_OFFSET = 10

__all__ = [
    'FRAME_WIDTH', 'FRAME_HEIGHT',
    'HAND_CONNECTOR_THICKNESS', 'HAND_LANDMARK_RADIUS',
    'WEB_LINE_THICKNESS', 'WEB_GLOW_THICKNESS',
    'SYMBIOTE_GLOW_RADIUS_OFFSET',
]
